const request = (query) => {
    if (query.includes('query stop')) {
        // HSL:1240118
        return {
            stop: {
                name: 'Kumpulan kampus',
                code: 'H3028',
                lat: 60.203978,
                lon: 24.965546,
                locationType: 'STOP',
            },
        }
    }
    if (query.includes('query nextDepartures')) {
        // HSL:4660297, startTime: 1640685900, maxDistance: 250
        return {
            stop: {
                name: 'Kanerva',
                code: 'V6697',
                lat: 60.2872,
                lon: 25.072,
                locationType: 'STOP',
                transfers: [
                    {
                        stop: {
                            name: 'Kanerva',
                            code: 'V6694',
                            gtfsId: 'HSL:4660294',
                            lat: 60.28773,
                            lon: 25.073433,
                            locationType: 'STOP',
                        },
                        distance: 118,
                    },
                ],
                stoptimesForPatterns: [
                    {
                        pattern: {
                            code: 'HSL:4711:1:01',
                            name: '711 to Hakaniemi (HSL:1111203)',
                            headsign: 'Hakaniemi',
                            route: {
                                mode: 'BUS',
                            },
                        },
                        stoptimes: [
                            {
                                scheduledDeparture: 44460,
                                realtimeDeparture: 44460,
                                scheduledArrival: 44460,
                                realtimeArrival: 44460,
                                realtime: false,
                                serviceDay: 1640642400,
                                stopSequence: 8,
                                trip: {
                                    gtfsId: 'HSL:4711_20211227_Ti_2_1212',
                                    routeShortName: '711',
                                    stoptimesForDate: [
                                        {
                                            stop: {
                                                code: 'V6148',
                                                name: 'Tikkurilan matkakesk',
                                                gtfsId: 'HSL:4610248',
                                                lat: 60.293834,
                                                lon: 25.044502,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 43920,
                                            realtimeArrival: 43920,
                                            scheduledDeparture: 43920,
                                            realtimeDeparture: 43920,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'V6136',
                                                name: 'Vaihdepolku',
                                                gtfsId: 'HSL:4610236',
                                                lat: 60.29838,
                                                lon: 25.0454,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 44040,
                                            realtimeArrival: 44040,
                                            scheduledDeparture: 44040,
                                            realtimeDeparture: 44040,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'V6227',
                                                name: 'Jokiniemen koulu',
                                                gtfsId: 'HSL:4620227',
                                                lat: 60.29821,
                                                lon: 25.05193,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 44100,
                                            realtimeArrival: 44100,
                                            scheduledDeparture: 44100,
                                            realtimeDeparture: 44100,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'V6217',
                                                name: 'Edvard Blomqvistin p',
                                                gtfsId: 'HSL:4620217',
                                                lat: 60.29845,
                                                lon: 25.05554,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 44160,
                                            realtimeArrival: 44160,
                                            scheduledDeparture: 44160,
                                            realtimeDeparture: 44160,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'V6205',
                                                name: 'Urheilutie',
                                                gtfsId: 'HSL:4620205',
                                                lat: 60.29549,
                                                lon: 25.0614,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 44220,
                                            realtimeArrival: 44220,
                                            scheduledDeparture: 44220,
                                            realtimeDeparture: 44220,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'V6699',
                                                name: 'Kunnaantie',
                                                gtfsId: 'HSL:4660299',
                                                lat: 60.29509,
                                                lon: 25.06703,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 44280,
                                            realtimeArrival: 44280,
                                            scheduledDeparture: 44280,
                                            realtimeDeparture: 44280,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'V6601',
                                                name: 'Hakintie',
                                                gtfsId: 'HSL:4660201',
                                                lat: 60.29136,
                                                lon: 25.07367,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 44340,
                                            realtimeArrival: 44340,
                                            scheduledDeparture: 44340,
                                            realtimeDeparture: 44340,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'V6697',
                                                name: 'Kanerva',
                                                gtfsId: 'HSL:4660297',
                                                lat: 60.2872,
                                                lon: 25.072,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 44460,
                                            realtimeArrival: 44460,
                                            scheduledDeparture: 44460,
                                            realtimeDeparture: 44460,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'V6425',
                                                name: 'Hovitie',
                                                gtfsId: 'HSL:4640225',
                                                lat: 60.28286,
                                                lon: 25.06756,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 44520,
                                            realtimeArrival: 44520,
                                            scheduledDeparture: 44520,
                                            realtimeDeparture: 44520,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'V6495',
                                                name: 'Nevatie',
                                                gtfsId: 'HSL:4640295',
                                                lat: 60.28049,
                                                lon: 25.07192,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 44640,
                                            realtimeArrival: 44640,
                                            scheduledDeparture: 44640,
                                            realtimeDeparture: 44640,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'V6491',
                                                name: 'Kuusikkokuja',
                                                gtfsId: 'HSL:4640291',
                                                lat: 60.27915,
                                                lon: 25.078957,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 44700,
                                            realtimeArrival: 44700,
                                            scheduledDeparture: 44700,
                                            realtimeDeparture: 44700,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'V6413',
                                                name: 'Kuusikkotie',
                                                gtfsId: 'HSL:4640213',
                                                lat: 60.27837,
                                                lon: 25.07894,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 44700,
                                            realtimeArrival: 44700,
                                            scheduledDeparture: 44700,
                                            realtimeDeparture: 44700,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'H3034',
                                                name: 'Viikki',
                                                gtfsId: 'HSL:1362142',
                                                lat: 60.22916,
                                                lon: 25.0124,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 45120,
                                            realtimeArrival: 45120,
                                            scheduledDeparture: 45120,
                                            realtimeDeparture: 45120,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'H3032',
                                                name: 'Koskelan varikko',
                                                gtfsId: 'HSL:1240123',
                                                lat: 60.21279,
                                                lon: 24.9702,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 45420,
                                            realtimeArrival: 45420,
                                            scheduledDeparture: 45420,
                                            realtimeDeparture: 45420,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'H3030',
                                                name: 'Sumatrantie',
                                                gtfsId: 'HSL:1240106',
                                                lat: 60.20699,
                                                lon: 24.967438,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 45420,
                                            realtimeArrival: 45420,
                                            scheduledDeparture: 45420,
                                            realtimeDeparture: 45420,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'H3028',
                                                name: 'Kumpulan kampus',
                                                gtfsId: 'HSL:1240118',
                                                lat: 60.203978,
                                                lon: 24.965546,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 45480,
                                            realtimeArrival: 45480,
                                            scheduledDeparture: 45480,
                                            realtimeDeparture: 45480,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'H3024',
                                                name: 'Vallilan varikko',
                                                gtfsId: 'HSL:1220104',
                                                lat: 60.19551,
                                                lon: 24.96272,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 45660,
                                            realtimeArrival: 45660,
                                            scheduledDeparture: 45660,
                                            realtimeDeparture: 45660,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'H3022',
                                                name: 'Ristikkokatu',
                                                gtfsId: 'HSL:1220102',
                                                lat: 60.19168,
                                                lon: 24.96451,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 45720,
                                            realtimeArrival: 45720,
                                            scheduledDeparture: 45720,
                                            realtimeDeparture: 45720,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'H2410',
                                                name: 'Sörnäinen (M)',
                                                gtfsId: 'HSL:1113131',
                                                lat: 60.187931,
                                                lon: 24.962369,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 45780,
                                            realtimeArrival: 45780,
                                            scheduledDeparture: 45780,
                                            realtimeDeparture: 45780,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'H2406',
                                                name: 'Haapaniemi',
                                                gtfsId: 'HSL:1112126',
                                                lat: 60.182608,
                                                lon: 24.956868,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'SCHEDULED',
                                            scheduledArrival: 45900,
                                            realtimeArrival: 45900,
                                            scheduledDeparture: 45900,
                                            realtimeDeparture: 45900,
                                            serviceDay: 1640556000,
                                        },
                                        {
                                            stop: {
                                                code: 'H2505',
                                                name: 'Hakaniemi',
                                                gtfsId: 'HSL:1111203',
                                                lat: 60.178205,
                                                lon: 24.951532,
                                                locationType: 'STOP',
                                            },
                                            pickupType: 'NONE',
                                            scheduledArrival: 46080,
                                            realtimeArrival: 46080,
                                            scheduledDeparture: 46080,
                                            realtimeDeparture: 46080,
                                            serviceDay: 1640556000,
                                        },
                                    ],
                                },
                            },
                        ],
                    },
                ],
            },
        }
    }
    if (query.includes('query nearest')) {
        // lat: 60.2872, lon: 25.072, maxDistance: 250
        return {
            nearest: {
                edges: [
                    {
                        node: {
                            place: {
                                name: 'Kanerva',
                                code: 'V6697',
                                gtfsId: 'HSL:4660297',
                                lat: 60.2872,
                                lon: 25.072,
                                locationType: 'STOP',
                                platformCode: null,
                                vehicleMode: 'BUS',
                            },
                            distance: 1,
                        },
                    },
                    {
                        node: {
                            place: {
                                name: 'Kanerva',
                                code: 'V6694',
                                gtfsId: 'HSL:4660294',
                                lat: 60.28773,
                                lon: 25.073433,
                                locationType: 'STOP',
                                platformCode: null,
                                vehicleMode: 'BUS',
                            },
                            distance: 112,
                        },
                    },
                ],
            },
        }
    }

    return undefined
}

module.exports = {
    api: { request },
}
