apiVersion: v1
kind: Service
metadata:
    name: tiralabra-cache
spec:
    ports:
        - port: 6379
          name: '6379'
          targetPort: 6379
    type: LoadBalancer
    selector:
        app: tiralabra-cache

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: tiralabra-cache
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tiralabra-cache
    template:
        metadata:
            labels:
                app: tiralabra-cache
        spec:
            hostname: tiralabra-cache
            containers:
                - name: tiralabra-cache
                  image: redis:latest
                  ports:
                      - containerPort: 6379
