apiVersion: v1
kind: Service
metadata:
    name: tiralabra-otp-hsl
spec:
    ports:
        - port: 8080
          name: '8080'
          targetPort: 8080
        - port: 8081
          name: '8081'
          targetPort: 8081
    type: LoadBalancer
    selector:
        app: tiralabra-otp-hsl

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: tiralabra-otp-hsl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tiralabra-otp-hsl
    template:
        metadata:
            labels:
                app: tiralabra-otp-hsl
        spec:
            hostname: tiralabra-otp-hsl
            containers:
                - name: tiralabra-otp-hsl
                  image: hsldevcom/opentripplanner:prod
                  ports:
                      - containerPort: 8080
                      - containerPort: 8081
                  env:
                      - name: ROUTER_NAME
                        value: hsl
                      - name: JAVA_OPTS
                        value: -Xmx5g
                      - name: ROUTER_DATA_CONTAINER_URL
                        value: https://api.digitransit.fi/routing-data/v2/hsl
